using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Models.Types;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DataConfigurations.EntitiesConfiguration
{
    public class CountryConfig : IEntityTypeConfiguration<Country>
    {


        public void Configure(EntityTypeBuilder<Country> builder)
        {
            builder.ToTable("Countries"); // Optional: explicitly set the table CountryName
            builder.HasKey(c => c.CountryId);
            builder.Property(c => c.CountryName).IsRequired().HasMaxLength(100);
            builder.Property(c => c.CountryCode).IsRequired().HasMaxLength(5);


            builder.HasData(
              CreateCountryFromEnum(EnCountryCode.AFG),
              CreateCountryFromEnum(EnCountryCode.ALB),
              CreateCountryFromEnum(EnCountryCode.DZA),
              CreateCountryFromEnum(EnCountryCode.AND),
              CreateCountryFromEnum(EnCountryCode.AGO),
              CreateCountryFromEnum(EnCountryCode.ATG),
              CreateCountryFromEnum(EnCountryCode.ARG),
              CreateCountryFromEnum(EnCountryCode.ARM),
              CreateCountryFromEnum(EnCountryCode.AUS),
              CreateCountryFromEnum(EnCountryCode.AUT),
              CreateCountryFromEnum(EnCountryCode.AZE),
              CreateCountryFromEnum(EnCountryCode.BHS),
              CreateCountryFromEnum(EnCountryCode.BHR),
              CreateCountryFromEnum(EnCountryCode.BGD),
              CreateCountryFromEnum(EnCountryCode.BRB),
              CreateCountryFromEnum(EnCountryCode.BLR),
              CreateCountryFromEnum(EnCountryCode.BEL),
              CreateCountryFromEnum(EnCountryCode.BLZ),
              CreateCountryFromEnum(EnCountryCode.BEN),
              CreateCountryFromEnum(EnCountryCode.BTN),
              CreateCountryFromEnum(EnCountryCode.BOL),
              CreateCountryFromEnum(EnCountryCode.BIH),
              CreateCountryFromEnum(EnCountryCode.BWA),
              CreateCountryFromEnum(EnCountryCode.BRA),
              CreateCountryFromEnum(EnCountryCode.BRN),
              CreateCountryFromEnum(EnCountryCode.BGR),
              CreateCountryFromEnum(EnCountryCode.BFA),
              CreateCountryFromEnum(EnCountryCode.BDI),
              CreateCountryFromEnum(EnCountryCode.CPV),
              CreateCountryFromEnum(EnCountryCode.KHM),
              CreateCountryFromEnum(EnCountryCode.CMR),
              CreateCountryFromEnum(EnCountryCode.CAN),
              CreateCountryFromEnum(EnCountryCode.CAF),
              CreateCountryFromEnum(EnCountryCode.TCD),
              CreateCountryFromEnum(EnCountryCode.CHL),
              CreateCountryFromEnum(EnCountryCode.CHN),
              CreateCountryFromEnum(EnCountryCode.COL),
              CreateCountryFromEnum(EnCountryCode.COM),
              CreateCountryFromEnum(EnCountryCode.COD),
              CreateCountryFromEnum(EnCountryCode.COG),
              CreateCountryFromEnum(EnCountryCode.CRI),
              CreateCountryFromEnum(EnCountryCode.CIV),
              CreateCountryFromEnum(EnCountryCode.HRV),
              CreateCountryFromEnum(EnCountryCode.CUB),
              CreateCountryFromEnum(EnCountryCode.CYP),
              CreateCountryFromEnum(EnCountryCode.CZE),
              CreateCountryFromEnum(EnCountryCode.DNK),
              CreateCountryFromEnum(EnCountryCode.DJI),
              CreateCountryFromEnum(EnCountryCode.DMA),
              CreateCountryFromEnum(EnCountryCode.DOM),
              CreateCountryFromEnum(EnCountryCode.ECU),
              CreateCountryFromEnum(EnCountryCode.EGY),
              CreateCountryFromEnum(EnCountryCode.SLV),
              CreateCountryFromEnum(EnCountryCode.GNQ),
              CreateCountryFromEnum(EnCountryCode.ERI),
              CreateCountryFromEnum(EnCountryCode.EST),
              CreateCountryFromEnum(EnCountryCode.SWZ),
              CreateCountryFromEnum(EnCountryCode.ETH),
              CreateCountryFromEnum(EnCountryCode.FJI),
              CreateCountryFromEnum(EnCountryCode.FIN),
              CreateCountryFromEnum(EnCountryCode.FRA),
              CreateCountryFromEnum(EnCountryCode.GAB),
              CreateCountryFromEnum(EnCountryCode.GMB),
              CreateCountryFromEnum(EnCountryCode.GEO),
              CreateCountryFromEnum(EnCountryCode.DEU),
              CreateCountryFromEnum(EnCountryCode.GHA),
              CreateCountryFromEnum(EnCountryCode.GRC),
              CreateCountryFromEnum(EnCountryCode.GRD),
              CreateCountryFromEnum(EnCountryCode.GTM),
              CreateCountryFromEnum(EnCountryCode.GIN),
              CreateCountryFromEnum(EnCountryCode.GNB),
              CreateCountryFromEnum(EnCountryCode.GUY),
              CreateCountryFromEnum(EnCountryCode.HTI),
              CreateCountryFromEnum(EnCountryCode.HND),
              CreateCountryFromEnum(EnCountryCode.HUN),
              CreateCountryFromEnum(EnCountryCode.ISL),
              CreateCountryFromEnum(EnCountryCode.IND),
              CreateCountryFromEnum(EnCountryCode.IDN),
              CreateCountryFromEnum(EnCountryCode.IRN),
              CreateCountryFromEnum(EnCountryCode.IRQ),
              CreateCountryFromEnum(EnCountryCode.IRL),
              CreateCountryFromEnum(EnCountryCode.ITA),
              CreateCountryFromEnum(EnCountryCode.JAM),
              CreateCountryFromEnum(EnCountryCode.JPN),
              CreateCountryFromEnum(EnCountryCode.JOR),
              CreateCountryFromEnum(EnCountryCode.KAZ),
              CreateCountryFromEnum(EnCountryCode.KEN),
              CreateCountryFromEnum(EnCountryCode.KIR),
              CreateCountryFromEnum(EnCountryCode.PRK),
              CreateCountryFromEnum(EnCountryCode.KOR),
              CreateCountryFromEnum(EnCountryCode.XKX),
              CreateCountryFromEnum(EnCountryCode.KWT),
              CreateCountryFromEnum(EnCountryCode.KGZ),
              CreateCountryFromEnum(EnCountryCode.LAO),
              CreateCountryFromEnum(EnCountryCode.LVA),
              CreateCountryFromEnum(EnCountryCode.LBN),
              CreateCountryFromEnum(EnCountryCode.LSO),
              CreateCountryFromEnum(EnCountryCode.LBR),
              CreateCountryFromEnum(EnCountryCode.LBY),
              CreateCountryFromEnum(EnCountryCode.LIE),
              CreateCountryFromEnum(EnCountryCode.LTU),
              CreateCountryFromEnum(EnCountryCode.LUX),
              CreateCountryFromEnum(EnCountryCode.MDG),
              CreateCountryFromEnum(EnCountryCode.MWI),
              CreateCountryFromEnum(EnCountryCode.MYS),
              CreateCountryFromEnum(EnCountryCode.MDV),
              CreateCountryFromEnum(EnCountryCode.MLI),
              CreateCountryFromEnum(EnCountryCode.MLT),
              CreateCountryFromEnum(EnCountryCode.MHL),
              CreateCountryFromEnum(EnCountryCode.MRT),
              CreateCountryFromEnum(EnCountryCode.MUS),
              CreateCountryFromEnum(EnCountryCode.MEX),
              CreateCountryFromEnum(EnCountryCode.FSM),
              CreateCountryFromEnum(EnCountryCode.MDA),
              CreateCountryFromEnum(EnCountryCode.MCO),
              CreateCountryFromEnum(EnCountryCode.MNG),
              CreateCountryFromEnum(EnCountryCode.MNE),
              CreateCountryFromEnum(EnCountryCode.MAR),
              CreateCountryFromEnum(EnCountryCode.MOZ),
              CreateCountryFromEnum(EnCountryCode.MMR),
              CreateCountryFromEnum(EnCountryCode.NAM),
              CreateCountryFromEnum(EnCountryCode.NRU),
              CreateCountryFromEnum(EnCountryCode.NPL),
              CreateCountryFromEnum(EnCountryCode.NLD),
              CreateCountryFromEnum(EnCountryCode.NZL),
              CreateCountryFromEnum(EnCountryCode.NIC),
              CreateCountryFromEnum(EnCountryCode.NER),
              CreateCountryFromEnum(EnCountryCode.NGA),
              CreateCountryFromEnum(EnCountryCode.MKD),
              CreateCountryFromEnum(EnCountryCode.NOR),
              CreateCountryFromEnum(EnCountryCode.OMN),
              CreateCountryFromEnum(EnCountryCode.PAK),
              CreateCountryFromEnum(EnCountryCode.PLW),
               CreateCountryFromEnum(EnCountryCode.PSE),
              CreateCountryFromEnum(EnCountryCode.PAN),
              CreateCountryFromEnum(EnCountryCode.PNG),
              CreateCountryFromEnum(EnCountryCode.PRY),
              CreateCountryFromEnum(EnCountryCode.PER),
              CreateCountryFromEnum(EnCountryCode.PHL),
              CreateCountryFromEnum(EnCountryCode.POL),
              CreateCountryFromEnum(EnCountryCode.PRT),
              CreateCountryFromEnum(EnCountryCode.QAT),
              CreateCountryFromEnum(EnCountryCode.ROU),
              CreateCountryFromEnum(EnCountryCode.RUS),
              CreateCountryFromEnum(EnCountryCode.RWA),
              CreateCountryFromEnum(EnCountryCode.KNA),
              CreateCountryFromEnum(EnCountryCode.LCA),
              CreateCountryFromEnum(EnCountryCode.VCT),
              CreateCountryFromEnum(EnCountryCode.WSM),
              CreateCountryFromEnum(EnCountryCode.SMR),
              CreateCountryFromEnum(EnCountryCode.STP),
              CreateCountryFromEnum(EnCountryCode.SAU),
              CreateCountryFromEnum(EnCountryCode.SEN),
              CreateCountryFromEnum(EnCountryCode.SRB),
              CreateCountryFromEnum(EnCountryCode.SYC),
              CreateCountryFromEnum(EnCountryCode.SLE),
              CreateCountryFromEnum(EnCountryCode.SGP),
              CreateCountryFromEnum(EnCountryCode.SVK),
              CreateCountryFromEnum(EnCountryCode.SVN),
              CreateCountryFromEnum(EnCountryCode.SLB),
              CreateCountryFromEnum(EnCountryCode.SOM),
              CreateCountryFromEnum(EnCountryCode.ZAF),
              CreateCountryFromEnum(EnCountryCode.ESP),
              CreateCountryFromEnum(EnCountryCode.LKA),
              CreateCountryFromEnum(EnCountryCode.SDN),
              CreateCountryFromEnum(EnCountryCode.SUR),
              CreateCountryFromEnum(EnCountryCode.SWE),
              CreateCountryFromEnum(EnCountryCode.CHE),
              CreateCountryFromEnum(EnCountryCode.SYR),
              CreateCountryFromEnum(EnCountryCode.TWN),
              CreateCountryFromEnum(EnCountryCode.TJK),
              CreateCountryFromEnum(EnCountryCode.TZA),
              CreateCountryFromEnum(EnCountryCode.THA),
              CreateCountryFromEnum(EnCountryCode.TLS),
              CreateCountryFromEnum(EnCountryCode.TGO),
              CreateCountryFromEnum(EnCountryCode.TON),
              CreateCountryFromEnum(EnCountryCode.TTO),
              CreateCountryFromEnum(EnCountryCode.TUN),
              CreateCountryFromEnum(EnCountryCode.TUR),
              CreateCountryFromEnum(EnCountryCode.TKM),
              CreateCountryFromEnum(EnCountryCode.TUV),
              CreateCountryFromEnum(EnCountryCode.UGA),
              CreateCountryFromEnum(EnCountryCode.UKR),
              CreateCountryFromEnum(EnCountryCode.ARE),
              CreateCountryFromEnum(EnCountryCode.GBR),
              CreateCountryFromEnum(EnCountryCode.USA),
              CreateCountryFromEnum(EnCountryCode.URY),
              CreateCountryFromEnum(EnCountryCode.UZB),
              CreateCountryFromEnum(EnCountryCode.VUT),
              CreateCountryFromEnum(EnCountryCode.VAT),
              CreateCountryFromEnum(EnCountryCode.VEN),
              CreateCountryFromEnum(EnCountryCode.VNM),
              CreateCountryFromEnum(EnCountryCode.YEM),
              CreateCountryFromEnum(EnCountryCode.ZMB),
              CreateCountryFromEnum(EnCountryCode.ZWE)
          );

        }


        private static Country CreateCountryFromEnum(EnCountryCode code)
        {
            return new Country
            {
                CountryId = (int)code,
                CountryName = ((EnCountryName)code).ToString().Replace("_", " "),  // To display space instead of underscore
                CountryCode = code.ToString()
            };
        }
    }
}

