using ModelDTO.ApplicationDTOs.User;
using Models.ApplicationModels;

namespace IServices.IApplicationServices.IServiceCategoryApplications.ILocalDrivingLicenseApplication;

public interface ICreateNewLocalDrivingLicenseApplication : ICreateService<CreateLocalDrivingLicenseApplicationRequest, LocalDrivingLicenseApplication>
{

}