using Models.ApplicationModels;

namespace IServices.IApplicationServices.IServiceCategoryApplications.ILocalDrivingLicenseApplication;

public interface ILocalDrivingLicenseApplicationRetrieve : IAsyncRetrieveService<LocalDrivingLicenseApplication, LocalDrivingLicenseApplication?>
{

}