using Models.ApplicationModels;

namespace IServices.IApplicationServices.IServiceCategoryApplications.ILocalDrivingLicenseApplication;

public interface IGetLocalDrivingLicenseApplication : IAsyncRetrieveService<LocalDrivingLicenseApplication, LocalDrivingLicenseApplication?>
{

}