using ModelDTO.ApplicationDTOs.User;
using Models.ApplicationModels;

namespace IServices.IApplicationServices.IServiceCategoryApplications.IRetakeTestApplication;

public interface INewRetakeTestApplicationCreator : ICreateService<CreateLocalDrivingLicenseApplicationRequest, LocalDrivingLicenseApplication>
{

}